# File: hosts.ini
#Adjust the IP addresses and user details as per your environment
[cassandra_nodes]
192.168.100.10
192.168.100.20
192.168.100.30

[cassandra_nodes:vars]
ansible_user=pdai108 
ansible_ssh_private_key_file=/home/pdai108/.ssh/id_ed25519 
ansible_become=yes
ansible_become_method=sudo
ansible_become_pass=MatKhauSudo  